# Generated by Django 3.2.8 on 2021-10-19 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('album_author', models.CharField(max_length=200)),
                ('album_img', models.ImageField(default='playlist_icon.jpg', upload_to='album_imgs')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='art_img')),
                ('biography', models.TextField(null=True)),
                ('followers_fans', models.ManyToManyField(blank=True, related_name='followers_fans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_color', models.CharField(max_length=200)),
                ('category_img', models.ImageField(default='category.jpg', upload_to='category_images')),
            ],
        ),
        migrations.CreateModel(
            name='Song_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('song_auther_written', models.CharField(max_length=200)),
                ('song_img', models.ImageField(upload_to='song_model_images')),
                ('song_path', models.FileField(upload_to='song_model_songs')),
                ('reference_name', models.CharField(max_length=200, null=True)),
                ('date_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_model', to='main.albums')),
                ('favorite', models.ManyToManyField(blank=True, related_name='favorite_song', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='song_name', to=settings.AUTH_USER_MODEL)),
                ('song_authers', models.ManyToManyField(blank=True, related_name='song_authers', to='main.Artists')),
                ('song_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.song_categories')),
            ],
        ),
        migrations.AddField(
            model_name='albums',
            name='album_artist',
            field=models.ManyToManyField(blank=True, related_name='album_artist', to='main.Artists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='album_favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albums',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='album_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
